name: Conditional check at runners

on:
  workflow_dispatch:  
    inputs:
      machine:
        type: choice
        description: 'The machine to run the automation on'
        options:
          - all
          - windows-latest
          - ubuntu-latest
          - ming

  push:
    branches:
      - feature*
      - master

  schedule:
    - cron: "0 12 * * *"

jobs:
  job-check:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ (github.event.inputs.machine == 'all' || github.event_name == 'push' || github.event_name == 'schedule') && steps.set-runners.outputs.runner || steps.set-runner.outputs.runner }}
    steps:
      - id: set-runners
        run: echo "::set-output name=runner::{\"runner\":[\"windows-latest\", \"macos-latest\", \"ubuntu-latest\"]}"
      - id: set-runner
        run: echo "::set-output name=runner::{\"runner\":[\"${{ github.event.inputs.machine }}\"]}"
  
  job-echo:
    needs: job-check
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: ${{ fromJSON(needs.job-check.outputs.runner) }}
    steps:
      - name: Print result
        run: |
          echo "The machine is: ${{ matrix.runner }}"
          echo "The branch is: ${{ github.ref_name }}"
          echo "The event is: ${{ github.event_name }}"
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          repository: "NTUEEboy/workflow-playground"
          token: ${{ secrets.PRIVATE_ACTIONS_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref_name }}
