name: Conditional check at runners

on:
  workflow_dispatch:  
    inputs:
      machine:
        descrition: 'The machine to run the automation on'
        require: true
        default: 'all'

  push:
    branches:
      - feature*
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ${{ (github.event_name == 'push' || github.event.inputs.machine == 'all') && matrix.runner || github.event.inputs.machine }}
    strategy:
      matrix:
        runner:
          [ming]
    steps:
      - name: Print result
        run: |
          echo "The machine is: ${{ (github.event_name == 'push' || github.event.inputs.machine == 'all') && matrix.runner || github.event.inputs.machine }}"
          echo "The branch is: ${{ github.ref_name }}"
          echo "The event is: ${{ github.event_name }}"

      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          repository: "NTUEEboy/workflow-playground"
          token: ${{ secrets.PRIVATE_ACTIONS_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref_name }}