name: Conditional check at runners

on:
  workflow_dispatch:  
    inputs:
      machine:
        type: choice
        description: 'The machine to run the automation on'
        options:
          - all
          - windows-latest
          - ubuntu-latest
          - ming

  push:
    branches:
      - feature*
      - master

  schedule:
    - cron: "0 12 * * *"

jobs:
  job-run-on-all:
    if: ${{ github.event.inputs.machine == 'all' || github.event_name == 'push' || github.event_name == 'schedule' }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          [ming,kiki]
    steps:
      - name: Print result
        run: |
          echo "The machine is: ${{ (github.event_name == 'push' || github.event.inputs.machine == 'all') && matrix.runner || github.event.inputs.machine }}"
          echo "The branch is: ${{ github.ref_name }}"
          echo "The event is: ${{ github.event_name }}"

      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          repository: "NTUEEboy/workflow-playground"
          token: ${{ secrets.PRIVATE_ACTIONS_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref_name }}

  job-run-on-one:
    if: ${{ github.event.inputs.machine != 'all' && github.event_name == 'workflow_dispatch' }}
    runs-on: ${{ github.event.inputs.machine }}
    steps:
      - name: Print result
        run: |
          echo "The machine is: ${{ (github.event_name == 'push' || github.event.inputs.machine == 'all') && matrix.runner || github.event.inputs.machine }}"
          echo "The branch is: ${{ github.ref_name }}"
          echo "The event is: ${{ github.event_name }}"

      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          repository: "NTUEEboy/workflow-playground"
          token: ${{ secrets.PRIVATE_ACTIONS_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref_name }}
