name: Clear Cache

on:
  workflow_dispatch:

jobs:
  job-check:
    runs-on: nz-z490-01
    defaults:
      run:
        shell: cmd
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo su
            docker restart ProcessQueue
          host: ubuntu@store.apistage.nzxt.com
          user: root
