name: Clear Cache

on:
  workflow_dispatch:

jobs:
  job-check:
    runs-on: nz-z490-01
    defaults:
      run:
        shell: cmd
    steps:
      - run: |
          ssh ubuntu@store.apistage.nzxt.com "sudo su; sudo docker restart ProcessQueue"
